# Generated by Django 5.2.10 on 2026-04-28 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('georegion', '0013_alter_georegion_region_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='georegion.georegion')),
                ('sub_region_kind', models.CharField(choices=[('country', 'country'), ('state', 'state'), ('admin_district', 'administrative district'), ('district', 'district'), ('admin_cooperation', 'administrative cooperation'), ('municipality', 'municipality'), ('borough', 'borough'), ('zipcode', 'zipcode'), ('admin_court_jurisdiction', 'administrative court jurisdiction')], default='admin_cooperation', max_length=30)),
            ],
            options={
                'verbose_name': 'election',
                'verbose_name_plural': 'elections',
            },
        ),
    ]
