# Generated by Django 5.2.15 on 2026-07-29 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('froide_election', '0001_initial'),
        ('georegion', '0014_georegion_related'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='sub_region_kind',
        ),
        migrations.CreateModel(
            name='RegionSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_region_kind', models.CharField(choices=[('country', 'country'), ('state', 'state'), ('admin_district', 'administrative district'), ('district', 'district'), ('admin_cooperation', 'administrative cooperation'), ('municipality', 'municipality'), ('borough', 'borough'), ('zipcode', 'zipcode'), ('admin_court_jurisdiction', 'administrative court jurisdiction')], default='admin_cooperation', max_length=30)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='georegion.georegion')),
            ],
        ),
        migrations.AddField(
            model_name='election',
            name='region_selections',
            field=models.ManyToManyField(to='froide_election.regionselection'),
        ),
    ]
